### PR TITLE
[SoC] Go-wechaty Github Actions Optimization

### PR DESCRIPTION
**Pull request by Nebell**
[核心目标](https://github.com/wechaty/summer-of-code/issues/8)的相关代码。

### CODE REVIEW

**Comment by Nebell** [comment]
因为一些Token还没有设置，所以有些步骤会失败。

**Review by dingdayu — CHANGES_REQUESTED** [review]
- Dockerfile 需要重新优化一下，最好使用多阶段构建。
你可以从： [Dockerfile](https://github.com/dingdayu/dnsx/blob/master/Dockerfile) 参考一下。
- 关于 `repository_dispatch` 我想应该还有在 [wechaty/go-wechaty](https://github.com/wechaty/go-wechaty) 的部分，需要在这里贴一下，方便查看和理解。
- 关于 `Win` 的部分，建议拆分出一个文件，那个目标的含义是跨平台，是想检测跨平台编译和运行的情况。

如果有不懂的可以随时微信联系我。

**Comment by Nebell** [comment]
对应 go-wechaty 部分 [https://github.com/wechaty/go-wechaty/pull/68](https://github.com/wechaty/go-wechaty/pull/68)

**Comment by dingdayu** [comment]
awesome, Like we communicated in WeChat.

Let's use `GH_TOKEN` instead of different tokens to facilitate debugging. 
If necessary, we will set the token separately.

about buildx: https://yeasy.gitbook.io/docker_practice/buildx/buildkit

It is recommended that buildx submit new PR.

**Comment by dingdayu** [comment]
> awesome, Like we communicated in WeChat.
> 
> Let's use `GH_TOKEN` instead of different tokens to facilitate debugging.
> If necessary, we will set the token separately.
> 
> about buildx: https://yeasy.gitbook.io/docker_practice/buildx/buildkit
> 
> It is recommended that buildx submit new PR.

**Comment by dingdayu** [comment]
抱歉，点错了 😂

**Review by dingdayu — APPROVED** [review]
LGTM

**Pull request merged**
